### ISSUE TITLE
Базовая реализация карточек FAQ.

### ISSUE THREAD

**Issue by GoddessEyes** [honeydev/junior#25]
- [x] Модель карточки вопроса.

- [x] Ответ администратора.

- [x] Ответы пользователей.

- [x] _Минимальный MarkDown для оформления вопроса_.

- [x] Управление ответами-вопросами в админ-панели.

**Comment by honeydev** [comment]
Давай не FAQ, семантически не подходит frequently asked questions - Часто Задаваемые Вопросы.
Лучше простой questions
